version: "3.1"
services:
  web:
    image: odoo:17.0
    container_name: odoo
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - DB_HOST=postgres-central
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=adminpass
      - DB_NAME=odoo_development
    env_file:
      - .env
    networks:
      - dev-network # ðŸ”¹ Agregado para conectar web a la misma red que db

networks:
  dev-network:
    external: true

volumes:
  odoo-web-data:
